name: Soia code generation

inputs:
  node-version:
    required: false
    type: string
    default: '20'
  working-directory:
    required: false
    type: string
    default: '.'

runs:
  using: 'composite'
  defaults:
    run:
      working-directory: ${{ inputs.working-directory }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Node dependencies
      run: npm ci

    - name: Run Soia code generation
      run: npm run soiac
